# Installs and starts PostgreSQL

---

- name: Install required packages
  ansible.builtin.dnf:
    name: '{{ package }}'
    state: present
  loop:
    - postgresql
    - postgresql-server
  loop_control:
    loop_var: package

- name: Install Python plugin required for Ansible community.postgresql collection
  ansible.builtin.pip:
    name: psycopg2-binary
    state: present

- name: Find out if PostgreSQL is initialized
  ansible.builtin.stat:
    path: /var/lib/pgsql/data/pg_hba.conf
  register: postgres_data

- name: Initialize PostgreSQL
  ansible.builtin.command: postgresql-setup initdb
  when: not postgres_data.stat.exists

- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Open port 5432
  ansible.posix.firewalld:
    port: 5432/tcp
    permanent: true
    immediate: true
    state: enabled