---

- name: Check if latest nodejs module is enabled
  ansible.builtin.command: 'dnf module list --enabled'
  changed_when: false
  register: dnf_response

- name: Enable latest version of nodejs
  ansible.builtin.command: 'dnf module enable -y nodejs'
  when: '"nodejs" not in dnf_response.stdout'

- name: Install latest version of nodejs
  ansible.builtin.dnf:
    name: nodejs
