# Sets up a server to host Discord bots and a database.

---

- name: Setup PostgreSQL database
  ansible.builtin.include_role:
    name: postgresql

- name: Setup nodejs and npm
  ansible.builtin.include_role:
    name: nodejs
